name: o_i18n_generator_example
description: Example of o_i18n_generator
version: 0.1.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  o_i18n_generator_example_source_package:
    path: example_source_package/

dev_dependencies:
  o_i18n_generator:
    path: ../