name: o_i18n_generator
description: Merges [language-tag].json files from given path in root and all dependant packages. Creates a map with translations. You can redirect (from one key to another), overwrite and fill missing translations with values from default language.
version: 0.1.0
homepage: https://github.com/owczaro/o_i18n_generator

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  equatable: ^1.2.5
  args: ^1.6.0
  dependency_visitor: ^0.1.4
  merge_map: ^1.0.2
  glob: ^1.2.0
  deep_collection: ^0.1.5+1
  dart_style: ^1.3.7
  yaml: ^2.2.1

dev_dependencies:
  effective_dart: ^1.2.4
  test: ^1.15.4
