///////////////////////////////////////////////////////////
///////////// AUTOGENERATED FILE. DO NOT MODIFY ///////////
///////////////////////////////////////////////////////////
// ignore_for_file: prefer_single_quotes

const Map<String, dynamic> enUS = {
  "language": "Language",
  "search": "Search",
  "example_source_package": {
    "key1": " Key 1",
    "group2": {
      "description": "Description from Group #2",
      "label": "Label from Group"
    },
    "group1": {
      "description": "Description from Group",
      "label": "Label from Group"
    }
  }
};
