import 'package:o_i18n_generator/o_i18n_generator.dart';
import 'en-US.g.dart';
import 'pl-PL.g.dart';

///////////////////////////////////////////////////////////
///////////// AUTOGENERATED FILE. DO NOT MODIFY ///////////
///////////////////////////////////////////////////////////

class LocaleLoader extends BasicLocaleLoader {
  @override
  List<String> get languageTags => ["en-US", "pl-PL"];
  @override
  Map<String, dynamic> loadTranslations(String languageTag) {
    switch (languageTag) {
      case 'pl-PL':
        return plPL;
      default:
        return enUS;
    }
  }
}
