///////////////////////////////////////////////////////////
///////////// AUTOGENERATED FILE. DO NOT MODIFY ///////////
///////////////////////////////////////////////////////////
// ignore_for_file: prefer_single_quotes

const Map<String, dynamic> plPL = {
  "language": "Język",
  "search": "Search",
  "example_source_package": {
    "key1": " Klucz 1",
    "group2": {
      "label": "-->example_source_package.group3.label",
      "description": "Opis z 2. grupy"
    },
    "group1": {"label": "Etykieta z grupy", "description": "Opis z grupy"}
  }
};
